# WebSocket address
websocket_url: ws://localhost:3001
# Token (set "" if no token is required)
access_token: ""
# Command prefix for bot commands
command_prefix: "/"
# Debug mode
debug: false
plugin:
  # directory without dot or slash(backslash in Windows) means relative path to working directory.
  directory: plugins
  # watch plugin directory for changes and reload automatically
  auto_reload: true