# Deprecated.
# WebSocket address
websocketUrl: ws://localhost:3001
# Token (set "" if no token is required)
accessToken: ""
# Command prefix for bot commands
commandPrefix: "/"
# Debug mode
debug: false
plugin:
  # directory without dot or slash(backslash in Windows) means relative path to working directory
  directory: plugins
  # watch plugin directory for changes and reload automatically
  autoReload: true
  # whether to load plugins bundled with the bot
  integrated:
    # integrated permission manager, set false if you want to use other permission manager
    permission: true
    # it will generate help of command by its description(if exists)
    helpGenerator: true