name: Publish to Maven Central

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Compute version name
        shell: bash
        run: |
          TAG="${GITHUB_REF_NAME}"
          VERSION="${TAG#v}"
          echo "RELEASE_VERSION=$VERSION" >> "$GITHUB_ENV"

      - name: Set gradle permissions
        run: chmod +x ./gradlew

      - name: Build artifacts (jar + sources + javadoc + shadowJar)
        run: ./gradlew --no-daemon clean build shadowJar
        env:
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}

      - name: Publish Maven artifacts to local staging repository
        run: |
          ./gradlew --no-daemon publishMavenJavaPublicationToLocalStagingRepository
        env:
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: JReleaser (Deploy Maven Central + Create GitHub Release + Upload assets)
        uses: jreleaser/jreleaser-action@v2
        with:
          arguments: deploy
        env:
#         JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_PROJECT_VERSION: ${{ env.RELEASE_VERSION }}
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Generate CHANGELOG
        id: changelog
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ contains(steps.version.outputs.version, 'SNAPSHOT') && 'Unreleased' || steps.version.outputs.version }}
          path: ./CHANGELOG.md

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.changelog.outputs.changes }}
          draft: false
          prerelease: ${{ contains(steps.version.outputs.version, 'alpha') || contains(steps.version.outputs.version, 'beta') || contains(steps.version.outputs.version, 'rc') || contains(steps.version.outputs.version, 'SNAPSHOT') }}
          files: |
            build/libs/*-all.jar
            build/libs/*-sources.jar
            build/libs/*-javadoc.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JReleaser out directory
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/libs/*.jar